// <auto-generated />
using AFKArena.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AFKArena.Migrations
{
    [DbContext(typeof(HeroContext))]
    [Migration("20190729233927_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AFKArena.Models.Hero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Accuracy");

                    b.Property<long>("Attack");

                    b.Property<double>("CritRating");

                    b.Property<long>("Defense");

                    b.Property<long>("Dodge");

                    b.Property<int>("Faction");

                    b.Property<long>("Haste");

                    b.Property<long>("Health");

                    b.Property<long>("LifeLeech");

                    b.Property<double>("MagicResist");

                    b.Property<string>("Name");

                    b.Property<double>("PhysicalResist");

                    b.Property<long>("Recovery");

                    b.Property<int>("Tier");

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
